# ----------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
# ----------------------------------------------------------------------------------

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - landingzones/lz-platform-identity
      - .pipelines/platform-identity.yml
      - .pipelines/templates/steps/deploy-platform-identity.yml

pr: none

resources:
  pipelines:
    # Trigger this pipeline when management-groups-ci pipeline completes
    - pipeline: ManagementGroups
      source: management-groups-ci
      trigger:
        branches:
          include:
            - refs/heads/main

variables:
- name: devops-org-name
  value: ${{ replace(replace(variables['System.CollectionUri'], 'https://dev.azure.com/' , ''), '/', '') }}
- name: variable-template-file
  value: ${{ variables['devops-org-name'] }}-${{ variables['Build.SourceBranchName'] }}.yml
- template: ../config/variables/common.yml
- template: ../config/variables/${{ variables['variable-template-file'] }}

pool:
  vmImage: $[ variables.vmImage ]

stages:

- stage: DeployPlatformIdentityStage
  displayName: Deploy Platform Identity Stage

  jobs:

  - deployment: DeployPlatformIdentityJob
    displayName: Deploy Platform Identity Job
    environment: ${{ variables['Build.SourceBranchName'] }}
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - template: templates/steps/load-log-analytics-vars.yml

          - template: templates/steps/show-variables.yml
            parameters:
              json: ${{ convertToJson(variables) }}

          - template: templates/steps/deploy-platform-identity.yml
            parameters:
              description: 'Deploy Identity - Private DNS Zones'
              moveTemplate: move-subscription.bicep
              templateFile: main.bicep
              deployOperation: ${{ variables['deployOperation'] }}
              workingDir: $(System.DefaultWorkingDirectory)/landingzones
